//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalClothBazarProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int oi_id { get; set; }
        public Nullable<int> oi_fk_o_id { get; set; }
        public int oi_quantity { get; set; }
        public Nullable<int> oi_fk_pro { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
